### ISSUE TITLE
Avoiding Exceptions during automatic testing

### ISSUE THREAD

**Issue by RainerHeintzmann** [JuliaInterop/JavaCall.jl#143]
JavaCall throws a `java.awt.HeadlessException` in Linux systems due to a missing "X11" display specification, when Git-Hub automatic testing is performed.  Does anyone know how to avoid this? Also on Mac the tests fail due to a missing java installation. Are there easy fixed for this?

**Comment by mkitti** [comment]
For Mac, set the `JAVA_HOME` environmental variable to tell JavaCall where to find Java. Where are you getting Java for Max from?

**Comment by mkitti** [comment]
I will get around to setting GitHub Actions CI here soon.

I would look into something like https://github.com/marketplace/actions/gabrielbb-xvfb-action

**Comment by RainerHeintzmann** [comment]
> For Mac, set the `JAVA_HOME` environmental variable to tell JavaCall where to find Java. Where are you getting Java for Mac from?

Sorry, my question was about GitHub's automatic testing on virtual machines. These tests work well on the Windows virtual machine (which seems to include a java installation) but they fail for the named reasons on Linux and Mac. Any experience how to fix this? Are there some configuration files to set up?

**Comment by aviks** [comment]
For headless Java, set `java.awt.headless=true`

**Comment by mkitti** [comment]
If you need to install Java, then use something like https://github.com/actions/setup-java

**Comment by RainerHeintzmann** [comment]
Thanks. This is in my `ci.yml` file in `.github\workflows`, but it seems to have no positive effect on the tests.
```yml
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: '11'
```
